### ISSUE TITLE
cx services balancer hostname case

### ISSUE THREAD

**Issue by nzoschke** [convox/praxis#117]
I tried to put the output of `cx services` into an OAuth callback and got a mismatch. There something weird going on between the balancer hostname being:

`https://interface-web.dev2-Balanc-1RXRI3NJLIE1M-1530036638.us-east-1.rack.convox.io`

But the browser turns it into:

`https://interface-web.dev2-balanc-1rxri3njlie1m-1530036638.us-east-1.rack.convox.io/auth`

**Comment by ddollar** [comment]
Seems outside the scope of Praxis. Suggesting lowercase?
