### ISSUE TITLE
AWS Stack Delete Failed

### ISSUE THREAD

**Issue by nzoschke** [convox/praxis#66]
Stacks don't delete cleanly on the first try:

```
13:12:53 UTC-0700	DELETE_FAILED	AWS::CertificateManager::Certificate	BalancerCertificate	Certificate arn:aws:acm:us-east-1:132866487567:certificate/9db897db-7862-4914-a071-c63eeb70f420 in account 132866487567 is in use.
```

A 2nd stack deletion seems to work.

**Comment by ddollar** [comment]
AWS bug. They know about it and will fix eventually.

We should make our uninstaller in Console try twice for now.
