### ISSUE TITLE
Local `cx env` verbosity

### ISSUE THREAD

**Issue by nzoschke** [convox/praxis#82]
I've gotten stuck on subtleties with the new local `cx env` behavior.

- `cx start` `ERROR: required env: HOST` could reference `convox env`. I mistakenly went down the .env file path
- `cx env set` accepts variables that are not in the manifest. It could offer a warning to add them.
- `cx env set` silence is too clever. It could say env set and restarting the app.

**Comment by ddollar** [comment]
Mostly fixed
